//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class condition
    {
        public condition()
        {
            this.CourseConditions = new HashSet<CourseCondition>();
            this.valueConditions = new HashSet<valueCondition>();
        }
    
        public string condition_name { get; set; }
        public string condition_type { get; set; }
        public int condition_id { get; set; }
    
        public virtual ICollection<CourseCondition> CourseConditions { get; set; }
        public virtual ICollection<valueCondition> valueConditions { get; set; }
    }
}
