//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public string course_name { get; set; }
        public int duration { get; set; }
        public System.DateTime commencement_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string location { get; set; }
        public string branch { get; set; }
        public string admin { get; set; }
        public string status { get; set; }
        public System.DateTime time { get; set; }
        public string createdBy { get; set; }
        public int courseno { get; set; }
        public int course_id { get; set; }
    }
}
