//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class implication
    {
        public implication()
        {
            this.CourseImplications = new HashSet<CourseImplication>();
        }
    
        public string implication_name { get; set; }
        public int id { get; set; }
        public string implication_type { get; set; }
    
        public virtual ICollection<CourseImplication> CourseImplications { get; set; }
    }
}
