//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dopEntities : DbContext
    {
        public dopEntities()
            : base("name=dopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<condition> conditions { get; set; }
        public DbSet<CourseCondition> CourseConditions { get; set; }
        public DbSet<CourseImplication> CourseImplications { get; set; }
        public DbSet<cours> courses { get; set; }
        public DbSet<implication> implications { get; set; }
        public DbSet<usercours> usercourses { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<valueCondition> valueConditions { get; set; }
        public DbSet<Remark> Remarks { get; set; }
    }
}
