//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class usercours
    {
        public int user_id { get; set; }
        public int course_id { get; set; }
        public string status { get; set; }
        public System.DateTime applyTime { get; set; }
        public int id { get; set; }
    }
}
